checkpoint:
  save_dir: ""
  callback:
    monitor: "validation / g_loss"
    save_top_k: -1
    verbose: True
    every_n_train_steps: 40000

wandb:
  project: ""
  entity: ""

trainer:
  gradient_clip_val: 0
  limit_val_batches: 0.0
  max_epochs: 100
  num_sanity_val_steps: 0
  fast_dev_run: False
  #val_check_interval: 500
  progress_bar_refresh_rate: 1
  strategy: 'ddp'
  benchmark: True
